name: loksewa
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: ^4.6.6
  wakelock_plus: ^1.1.4
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  flutter_form_builder: ^9.2.1
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  qr_code_dart_scan: ^0.7.5
  firebase_core: ^2.25.5
  toggle_switch: ^2.1.0
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  search_page: ^2.3.0
  card_swiper: ^3.0.1
  intl: ^0.19.0
  fluttertoast: ^8.2.10
  eva_icons_flutter: ^3.1.0
  flutter_quill: ^10.8.5
  flutter_speed_dial: ^7.0.0
  lottie_screen_onboarding_flutter: ^1.1.3
  provider: ^6.1.2
  table_calendar: ^3.1.3
  collection: ^1.18.0
  socket_io_client: ^3.0.2
  nepali_utils: ^3.0.6
  device_preview: ^1.2.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/


  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter.ttf
          weight: 400

    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/robotoblack.ttf
          weight: 400
